// CPPY Version 0.1
#ifndef CPPY
#define CPPY

#include "cppy/all.h"
#include "cppy/any.h"
#include "cppy/ascii.h"
#include "cppy/bin.h"
#include "cppy/boolean.h"
#include "cppy/callable.h"
#include "cppy/divmod.h"
#include "cppy/enumerate.h"
#include "cppy/exec.h"
#include "cppy/filter.h"
#include "cppy/format.h"
#include "cppy/floatp.h"
#include "cppy/hash.h"
#include "cppy/hex.h"
#include "cppy/input.h"
#include "cppy/integer.h"
#include "cppy/issubclass.h"
#include "cppy/len.h"
#include "cppy/map.h"
#include "cppy/max.h"
#include "cppy/memoryview.h"
#include "cppy/min.h"
#include "cppy/oct.h"
#include "cppy/ord.h"
#include "cppy/print.h"
#include "cppy/range.h"
#include "cppy/reversed.h"
#include "cppy/round.h"
#include "cppy/str.h"
#include "cppy/sum.h"
#include "cppy/slice.h"
#include "cppy/sorted.h"
#include "cppy/type.h"
#include "cppy/zip.h"

#endif